#tag::mn[]
micronaut:
    application:
        name: bookinventory
    server:
        port: 8082
#end::mn[]
#tag::consul[]
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
#end::consul[]
